name: music-box

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:       

jobs:
  musicbox:
    name: Update Music Box Gist
    runs-on: ubuntu-latest
    environment: music-box
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Update
        uses: ./
        env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
